name: Publish

on:
  push:
  issue_comment:

jobs:
  clamav:
    name: Run ClamAV (Linux mainly)

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install ClamAV & Scan
        id: scan
        run: |
          sudo apt install clamav clamav-daemon clamav-freshclam

          sudo clamd
          sudo freshclam
          sudo clamdscan /data/samples/
        continue-on-error: true

      - name: Check scan results
        if: steps.scan.outputs.exitcode != '0'
        run: |
          echo "Virus/malware detected! Please check the logs."
          exit 1
